import { Options } from './../type/index';
declare class FineSwiper {
    private root;
    private direction;
    private loop;
    private auto;
    private delayed;
    private effect;
    private startTime;
    private callBack;
    private startingPoint;
    private isTracking;
    private captureClick;
    private disabledHandSlideing;
    private timer;
    private defaultIndex;
    private slider;
    private children;
    private length;
    private scaleSize;
    private index;
    private will;
    private speed;
    private scaleWidth;
    private scaleHeight;
    private _start;
    private _move;
    private _end;
    private _closeDefault;
    constructor(options: Options);
    private closeDefault;
    private initFromEffect;
    private ifEffectSlide;
    private ifEffectFade;
    private initSetIndex;
    private stopDraggable;
    private setInterval;
    private clear;
    private start;
    private move;
    private end;
    private fadeProcess;
    private slideProcess;
    private fadeSetIndex;
    private numericalConversion;
    moveTo(index: number): void;
    private aotoplay;
    private slideMove;
    private fadeMove;
    private startMove;
    destroy(): void;
}
export default FineSwiper;
